/*
 * name2add.c:
 * this file was automaticly generated by gen_name2add
 */
#include <stdio.h>
#include <name2add.h>

__name2add __n2a[] =
{
  {"sys_fork", 0xf8f8f8f8},
  {"sys_read", 0xf8f8f7f7},
  {"sys_write", 0xf8f8f6f6},
  {"sys_exit", 0xf8f8f5f5},
  {"sys_setuid", 0xf8f8f4f4},
  {"sys_setgid", 0xf8f8f3f3},
  {"sys_getuid", 0xf8f8f2f2},
  {"sys_getgid", 0xf8f8f1f1},
  {"sys_open", 0xf8f8f0f0},
  {"sys_close", 0xf8f8efef},
  {"kmalloc", 0xf8f8eeee},
  {NULL, 0}
};

/*
 * name2add.c:
 * this file was automaticly generated by gen_name2add
 */
#include <stdio.h>
#include <name2add.h>

__name2add __n2a[] =
{
  {"sys_fork", 0xf8f8f8f8},
  {"sys_read", 0xf8f8f7f7},
  {"sys_write", 0xf8f8f6f6},
  {"sys_exit", 0xf8f8f5f5},
  {"sys_setuid", 0xf8f8f4f4},
  {"sys_setgid", 0xf8f8f3f3},
  {"sys_getuid", 0xf8f8f2f2},
  {"sys_getgid", 0xf8f8f1f1},
  {"sys_open", 0xf8f8f0f0},
  {"sys_close", 0xf8f8efef},
  {"kmalloc", 0xf8f8eeee},
  {NULL, 0}
};

