/*
 * addresses.h:
 * this file was automaticly generated by gen_defines
 */
#define SYS_FORK_ADD 0xf8f8f8f8
#define SYS_READ_ADD 0xf8f8f7f7
#define SYS_WRITE_ADD 0xf8f8f6f6
#define SYS_EXIT_ADD 0xf8f8f5f5
#define SYS_SETUID_ADD 0xf8f8f4f4
#define SYS_SETGID_ADD 0xf8f8f3f3
#define SYS_GETUID_ADD 0xf8f8f2f2
#define SYS_GETGID_ADD 0xf8f8f1f1
#define SYS_OPEN_ADD 0xf8f8f0f0
#define SYS_CLOSE_ADD 0xf8f8efef
#define KMALLOC_ADD 0xf8f8eeee
/*
 * addresses.h:
 * this file was automaticly generated by gen_defines
 */
#define SYS_FORK_ADD 0xf8f8f8f8
#define SYS_READ_ADD 0xf8f8f7f7
#define SYS_WRITE_ADD 0xf8f8f6f6
#define SYS_EXIT_ADD 0xf8f8f5f5
#define SYS_SETUID_ADD 0xf8f8f4f4
#define SYS_SETGID_ADD 0xf8f8f3f3
#define SYS_GETUID_ADD 0xf8f8f2f2
#define SYS_GETGID_ADD 0xf8f8f1f1
#define SYS_OPEN_ADD 0xf8f8f0f0
#define SYS_CLOSE_ADD 0xf8f8efef
#define KMALLOC_ADD 0xf8f8eeee
